name: ReportSPN
main: ReportUI\SPNVN\Main
api:
 - 3.0.0
 - 4.0.0
author: BlackPMFury
depend: FormAOI
version: 6.0
description: "Report Without Console's Permission."
commands:
 tocao:
  description: "Hệ Thống Tố Cáo Người Chơi Phạt Luận"
  default: true